### ISSUE TITLE
Analyze (explain) To Do

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb-cli#1030]
1. [ ] Fix correlation between attributes and computables [in edgedb](https://github.com/edgedb/edgedb/issues/5183)
2. [ ] Provide fine-grained (\expand) output as nice as coarse-grained (i.e look like #1027)
3. [ ] Figure out what's left in `analyze` command (#989)
4. [ ] Debug output (which is a full, unoptimized postgres' tree) should also be formatted similarly to fine-grained output

**Comment by msullivan** [comment]
See also 
- [ ] https://github.com/edgedb/edgedb/issues/5183 
- [ ] https://github.com/edgedb/edgedb/issues/7699
