### ISSUE TITLE
edgedb server implementation (RFC 1001)

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#64]
This tracks the implementation of [RFC 1001 - Server Installation and Control](https://github.com/edgedb/rfcs/blob/master/text/1001-edgedb-server-control.rst).

- [x] `edgedb server install` (#65, #66, #67, #68)
- [x] `edgedb server uninstall` (#175)
- [x] `edgedb server init` (#69)
- [x] `edgedb server start|stop|restart|status` (#70, #71, #72)
- [x] `edgedb server list`
- [x] `edgedb server logs`
- [x] `edgedb server upgrade` (#80)
